### ISSUE TITLE
Problems with subscribing to announcements

### ISSUE THREAD

**Issue by BrownBurger** [bitcoin-core/bitcoincore.org#622] opened 2018-10-18 09:58 UTC
I've tried to subscribe to the announcements several times using email addresses from different provides such as Gmail and GMX. I checked my inbox and spam folder. But unfortunately I've never received a confirmation email.

**Comment by harding** [comment] 2018-10-18 11:03
@BrownBurger yes, unfortunately, the announcements list is known to be dead.  PR #610 redirects people to following an RSS feed, but that PR hasn't received any review yet.  If it takes much longer to get review, perhaps I'll just delete the announcements text in the meantime so we aren't wasting the time of people such as yourself (sorry about that).

Closing this issue as a duplicate of a known issue, but thanks for reporting!

**Closed by harding** 2018-10-18 11:03 UTC
