### ISSUE TITLE
Problems viewing web site pages this last couple of days

### ISSUE THREAD

**Issue by ab-test** [bitcoin-core/bitcoincore.org#101] opened 2016-02-02 09:13 UTC
Great site but in the last few days when I view the site I have often seen all the content missing.  Just went to this page now:  https://bitcoincore.org/en/blog/   On this page in the content area all I see is:

Blog

Show your support

Nothing in between. 

Same time I check the language drop down and see just "English" as an option.  However I am sure I saw other language options before.

Checking the contribute page: https://bitcoincore.org/en/contribute/ I see this:

Page Not Found

Sorry, but the page you were trying to view does not exist, try searching for it below.

Other things to try:

Search https://bitcoincore.org:

I refreshed my browser and same appears on Chrome and Safari browsers.  

Right now the only page that seems to be working is: https://bitcoincore.org/en/supporters

Regards

**Comment by ab-test** [comment] 2016-02-02 09:19
Not sure if this helps but I notice some of your links are like this and do not work:

https://bitcoincore.org/en/2015/12/23/capacity-increases-faq/

If I enter this without the trailing "/" then it works:

https://bitcoincore.org/en/2015/12/23/capacity-increases-faq

**Comment by btcdrak** [comment] 2016-02-02 09:20
I am aware of the issue and the cause.

**Comment by ab-test** [comment] 2016-02-02 09:24
Okay good to hear that.  Great website by the way!  Really happy to see this up and hope that going forward it can help others to get a better idea of the huge amount of work that's been done by bitcoin core developers.

**Comment by btcdrak** [comment] 2016-02-02 12:08
Should be more or less fixed now. There are still a few things to take care of. The cause was an upgrade to Jekyll 3.

**Comment by btcdrak** [comment] 2016-02-04 02:24
This appears to be solved fully.

**Closed by btcdrak** 2016-02-04 02:24 UTC
Labels: bug
