### ISSUE TITLE
List all new content on front page

### ISSUE THREAD

**Issue by dexX7** [bitcoin-core/bitcoincore.org#73] opened 2016-01-25 18:23 UTC
When just looking at the "recent posts", it seems like there is less progress than there actually is.

In my opinion it would be nice, if new content would be immediately visible on the front page, such as new posts about the dev meetings.

On a related note: some kind of newsletter to inform about new posts would be nice, too.

**Comment by btcdrak** [comment] 2016-01-25 18:32
@dexX7 Yes a proper front page is planned. A newsletter is on my wishlist of todos. For now you can use RSS and/or subscribe to the twitter feed [@bitcoincoreorg](https://twitter.com/bitcoincoreorg)

**Comment by btcdrak** [comment] 2016-04-22 09:38
duplicate of #29

**Closed by btcdrak** 2016-04-22 09:38 UTC
Labels: discussion, duplicate, enhancement
