### ISSUE TITLE
Site does not reflect current source repo content

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-core/bitcoincore.org#539] opened 2018-04-23 14:34 UTC
After the merge of the lifecylce fixup, the page seems stuck: https://bitcoincore.org/en/lifecycle/

**Comment by harding** [comment] 2018-04-23 16:02
It also didn't build the previous merge for PR 536.  Upon noticing that a few days ago, I contacted an admin for the build server who is planning to investigate when he's next in the office.

**Comment by MarcoFalke** [comment] 2018-04-25 17:04
@harding Any response or further debugging details on the GitHub pages thing?

**Comment by harding** [comment] 2018-04-25 17:34
@MarcoFalke per a brief discussion yesterday in #bitcoin-core-dev IRC, @TheBlueMatt doesn't have the credentials to login from his current location to begin investigating.  I previously told him that I didn't think the issue is urgent (and I still don't) unless there are upcoming releases or security announcements we need to push out.

I don't know how much of the administration of the build/hosting servers is intended to be private, so you might want to contact him privately for further discussion of the issue.  (I'm happy to help, of course.)

**Comment by TheBlueMatt** [comment] 2018-04-25 17:46
Should be fixed now.

**Comment by MarcoFalke** [comment] 2018-04-25 17:56
Ah. I wasn't aware of how the site is set up. Thanks for fixing.

**Closed** 2018-04-25 17:56 UTC

**Comment by harding** [comment] 2018-04-25 18:01
@TheBlueMatt Thanks!
